name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.x
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.6.12
      - name: Install
        run: pnpm i
      - name: Build
        run: pnpm run build
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test
        env:
          FORCE_COLOR: 1
      # - name: Publish Unit Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v1
      #   if: always()
      #   with:
      #     files: junit.xml
